{ inputs, ... }:
let
  system = "x86_64-linux";

  pkgs = import inputs.nixpkgs {
    inherit system;
    overlays = [ inputs.bun2nix.overlays.default ];
  };

  # Reproducible build: node_modules + web assets are built on the Nix builder
  # (bun.nix is generated by `bunx bun2nix -o bun.nix`), so nothing is installed
  # or compiled on the VM at runtime.
  apolloApp = pkgs.bun2nix.writeBunApplication {
    pname = "apollo";
    version = "1.0.0";

    src = ./.;

    bunDeps = pkgs.bun2nix.fetchBunDeps { bunNix = ./bun.nix; };

    # Tailwind's native engine (oxide) needs libstdc++/libgcc while building the
    # CSS. autoPatchElf is avoided because sharp ships musl-libc variants that
    # cannot be patched on glibc; sharp is an optional baileys dependency that
    # is never exercised here (Apollo only receives images), so its unpatched
    # natives are harmless at runtime.
    buildPhase = ''
      export LD_LIBRARY_PATH=${pkgs.lib.makeLibraryPath [ pkgs.stdenv.cc.cc.lib ]}
      bun run build:web
    '';
    dontUseBunCheck = true;
    startScript = "bun run src/index.ts";

    runtimeInputs = with pkgs; [
      bash
      coreutils
      curl
      git
      gnugrep
      gnused
      jq
      ripgrep
    ];
  };
in
{
  microvm.vms.apollo = {
    autostart = true;

    config =
      { lib, pkgs, ... }:
      let
        port = 8080;

        secrets = builtins.fromJSON (builtins.readFile ./secrets.json);

        authJson = pkgs.writeText "apollo-auth.json" (
          builtins.toJSON {
            anthropic = {
              access = secrets.anthropicOauth;
              # Long-lived setup token with no refresh token; far-future expiry so pi
              # uses it directly and never attempts a refresh.
              expires = 4102444800000;
              refresh = "";
              type = "oauth";
            };
          }
        );

        setup = pkgs.writeShellScript "apollo-setup" ''
          set -euo pipefail
          export PATH=${lib.makeBinPath [ pkgs.coreutils ]}:$PATH

          agentDir="$HOME/.pi/agent"
          mkdir -p "$agentDir/sessions" "$agentDir/skills" "$HOME/whatsapp"

          # SYSTEM_PROMPT.md is the agent's system prompt
          ln -sfn ${./agent/SYSTEM_PROMPT.md} "$agentDir/SYSTEM_PROMPT.md"

          # Seed OAuth credentials once; pi refreshes and persists them afterwards
          if [ ! -s "$agentDir/auth.json" ]; then
            install -m600 ${authJson} "$agentDir/auth.json"
          fi
        '';
      in
      {
        microvm = {
          hypervisor = "qemu";
          mem = 4096;
          vcpu = 2;

          interfaces = [
            {
              id = "vm-apollo";
              mac = "52:54:00:3e:a2:c3";
              type = "tap";
            }
          ];

          shares = [
            {
              mountPoint = "/nix/.ro-store";
              proto = "virtiofs";
              source = "/nix/store";
              tag = "ro-store";
            }
          ];

          volumes = [
            {
              image = "var.img";
              mountPoint = "/var";
              size = 40960;
            }
          ];
        };

        environment.systemPackages = with pkgs; [
          bun
          curl
          git
          jq
          ripgrep
        ];

        networking = {
          firewall.allowedTCPPorts = [ port ];
          hostName = "apollo";
          useNetworkd = true;
        };

        security.sudo.wheelNeedsPassword = false;

        services = {
          beszel.agent = {
            enable = true;
            environment.KEY = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILRp6cIsh8pO+LF+s1qe1Zl5v/sZWlR23GcCow7g6D7L";
            openFirewall = true;
          };

          openssh = {
            enable = true;

            hostKeys = [
              {
                path = "/var/lib/ssh-host-keys/ssh_host_ed25519_key";
                type = "ed25519";
              }
              {
                path = "/var/lib/ssh-host-keys/ssh_host_rsa_key";
                type = "rsa";
              }
            ];

            settings.PermitRootLogin = "yes";
          };
        };

        system.stateVersion = "26.05";

        systemd = {
          network = {
            enable = true;

            networks."20-lan" = {
              matchConfig.Type = "ether";
              networkConfig.DHCP = "yes";
            };
          };

          services.apollo = {
            description = "Apollo WhatsApp assistant (pi SDK + Baileys)";

            after = [ "network-online.target" ];
            requires = [ "network-online.target" ];
            wantedBy = [ "multi-user.target" ];

            environment = {
              APOLLO_ALLOW_FROM = secrets.mainNumber;
              APOLLO_MODEL = "anthropic/claude-sonnet-5";
              APOLLO_THINKING = "medium";
              APOLLO_WORKSPACE = "%t/apollo/workspace";
              HOME = "%S/apollo";
              PORT = toString port;
              SSL_CERT_FILE = "/etc/ssl/certs/ca-certificates.crt";
            };

            serviceConfig = {
              DynamicUser = true;
              ExecStart = "${apolloApp}/bin/apollo";
              ExecStartPre = setup;
              Restart = "on-failure";
              RestartSec = "10s";
              RuntimeDirectory = "apollo/workspace";
              StateDirectory = "apollo";
              WorkingDirectory = "%S/apollo";
            };
          };
        };

        time.timeZone = "Europe/Vienna";

        users.users.roman = {
          extraGroups = [ "wheel" ];
          isNormalUser = true;
          openssh.authorizedKeys.keys = [
            "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC2UfiONg3o2mydlSFdpIRWD9lRc+F/QK2GtHJPe3hYADJMFq+59gpYpuzA8Ccya6wGxkSUgcAWP5rqbidfsD08NzxQgCGz2HWyD0if0FkM2eeqOlOuJ5ymJ7NWnF1AQQBNE27UIPUW+beTlDCZEUZubSSfe87PEKbYgTeV7bO4BlXOzO+JI4AqUEuxQ5T6oFpUtKt+SepslsMECJZQnTBJBAITXBaBTwJwHYdNYx5WeK8+ObILPgapA0/l1/5y+zXBrU4ZH4xMSmlFNnt9iQxikrVXlWJvmieDfyPmkJSCJblqnhEmEgIyi+w/iPH5IwXaX8dwfp2mLM3ULSC5XvRPX7Pqs9gRmYAlaaFB7NEG2sEr8pWSq0Ag4enILp1otEvCLJtc/pbNa60rXiLpioOQ3kgsoMizsOHzqR7CN834dH3AK49zSKjEFVZLugzrB/GTsNH04+oQXbuDW04ok4b7xdy7fMPIA3I6TkaSHDfWAQ3DqaYdtmRzqlH3iljpVrTF6Mkjwuw8GZskblpx7AJXT7iH3CGXOVIf/qJnk806eDGKFwKLT/Pr86crmxbGdqiMIIM6UJ+0Ka+MMgaRrwi6h9FIRNUL6QM7/zC0QwNBxdGYtSOx58Z0qZ/LGqwm1qel2w0WIOkirbxLvk4Rbo+HedAZ8K38z9B7ZcCiN/U7bQ== roman@lerchster.dev"
          ];
        };
      };
  };
}
