{ inputs, ... }:
let
  system = "x86_64-linux";

  pkgs = import inputs.nixpkgs {
    inherit system;
    overlays = [ inputs.bun2nix.overlays.default ];
  };

  # Tool sets shared across the app and the systemd units, defined once here.
  # agentPkgs: everything the agent shells out to. gitPkgs: what the git backup
  # and bootstrap scripts need. (Guest units reference these host-eval lists,
  # as they already do for apolloApp.)
  agentPkgs =
    (with pkgs; [
      bash
      bun
      coreutils
      curl
      ffmpeg-headless
      file
      git
      gnugrep
      gnused
      gnutar
      gzip
      imagemagick
      jq
      mermaid-cli
      openssh
      p7zip
      poppler-utils
      python3
      ripgrep
      tesseract
      unzip
      xz
      yt-dlp
      zip
      zstd
    ])
    ++ [ inputs.proton-cli.packages.${system}.default ];

  gitPkgs = with pkgs; [
    bash
    coreutils
    git
    openssh
  ];

  # Reproducible build: node_modules + web assets are built on the Nix builder
  # (bun.nix is generated by `bunx bun2nix -o bun.nix`), so nothing is installed
  # or compiled on the VM at runtime.
  apolloApp = pkgs.bun2nix.writeBunApplication {
    pname = "apollo";
    version = "1.0.0";

    src = ./.;

    bunDeps = pkgs.bun2nix.fetchBunDeps { bunNix = ./bun.nix; };

    # Tailwind's native engine (oxide) needs libstdc++/libgcc while building the
    # CSS. autoPatchElf is avoided because sharp ships musl-libc variants that
    # cannot be patched on glibc; sharp is an optional baileys dependency that
    # is never exercised here (Apollo only receives images), so its unpatched
    # natives are harmless at runtime.
    buildPhase = ''
      export LD_LIBRARY_PATH=${pkgs.lib.makeLibraryPath [ pkgs.stdenv.cc.cc.lib ]}
      bun run build:web
    '';
    dontUseBunCheck = true;
    startScript = "bun run src/index.ts";

    runtimeInputs = agentPkgs;
  };
in
{
  microvm.vms.apollo = {
    autostart = true;

    config =
      { lib, pkgs, ... }:
      let
        port = 8080;

        checks = import ../monitoring/checks.nix { inherit lib pkgs; };

        secrets = builtins.fromJSON (builtins.readFile ./secrets.json);

        protonCli = inputs.proton-cli.packages.${pkgs.stdenv.hostPlatform.system}.default;

        # Chromium for the browser skill's managed-local sessions. chrome-launcher (inside
        # `browse`) picks it up via CHROME_PATH; the flags are the standard headless-in-a-VM
        # pair - no user-namespace sandbox, and no reliance on a large /dev/shm.
        chromeWrapper = pkgs.writeShellScript "apollo-chrome" ''
          exec ${pkgs.chromium}/bin/chromium --no-sandbox --disable-dev-shm-usage "$@"
        '';

        # The bot's WhatsApp avatar: the dashboard favicon rendered to a 640x640 JPEG at
        # build time (librsvg rasterizes the SVG onto the brand indigo, magick encodes the
        # JPEG), so the app just uploads the bytes - no runtime image library needed.
        profilePicture =
          pkgs.runCommand "apollo-profile-picture.jpg"
            {
              nativeBuildInputs = [
                pkgs.imagemagick
                pkgs.librsvg
              ];
            }
            ''
              rsvg-convert --width 640 --height 640 --background-color '#6366f1' ${./src/favicon.svg} --output icon.png
              magick icon.png -quality 90 jpg:$out
            '';

        setup = pkgs.writeShellScript "apollo-setup" ''
          set -euo pipefail
          export PATH=${lib.makeBinPath [ pkgs.coreutils ]}:$PATH

          agentDir="$HOME/.pi/agent"
          mkdir -p "$agentDir/sessions" "$agentDir/extensions" "$HOME/whatsapp"

          # Recreate skills/ from scratch each start: the entries are all store symlinks, and a stale
          # real directory left by an earlier layout would silently shadow `ln -sfn` (which cannot
          # replace a real dir), pinning a skill to an old version across deploys.
          rm -rf "$agentDir/skills"
          mkdir -p "$agentDir/skills"

          # SYSTEM_PROMPT.md is the agent's system prompt
          ln -sfn ${./agent/SYSTEM_PROMPT.md} "$agentDir/SYSTEM_PROMPT.md"

          # COMPACTION_PROMPT.md overrides how the session is summarized on compaction
          ln -sfn ${./agent/COMPACTION_PROMPT.md} "$agentDir/COMPACTION_PROMPT.md"

          # MEMORY_PROMPT.md governs how MEMORY.md is folded forward when the conversation is quiet
          ln -sfn ${./agent/MEMORY_PROMPT.md} "$agentDir/MEMORY_PROMPT.md"

          # Skills pi discovers from $agentDir/skills (read-only)
          ln -sfn ${../../../../shared/modules/pi/skills/browser} "$agentDir/skills/browser"
          ln -sfn ${../../../../shared/modules/pi/skills/context7} "$agentDir/skills/context7"
          ln -sfn ${../../../../shared/modules/pi/skills/exa} "$agentDir/skills/exa"
          ln -sfn ${./agent/skills/backup} "$agentDir/skills/backup"
          ln -sfn ${./agent/skills/briefing} "$agentDir/skills/briefing"
          ln -sfn ${./agent/skills/diagram} "$agentDir/skills/diagram"
          ln -sfn ${./agent/skills/files} "$agentDir/skills/files"
          ln -sfn ${./agent/skills/image} "$agentDir/skills/image"
          ln -sfn ${./agent/skills/macros} "$agentDir/skills/macros"
          ln -sfn ${./agent/skills/obsidian} "$agentDir/skills/obsidian"
          ln -sfn ${./agent/skills/offers} "$agentDir/skills/offers"
          ln -sfn ${./agent/skills/proton} "$agentDir/skills/proton"
          ln -sfn ${./agent/skills/recall} "$agentDir/skills/recall"
          ln -sfn ${./agent/skills/reminders} "$agentDir/skills/reminders"
          ln -sfn ${./agent/skills/weather} "$agentDir/skills/weather"

          # Extensions pi discovers from $agentDir/extensions. directory-agents-md
          # injects each vault folder's AGENTS.md on read/write/edit.
          ln -sfn ${../../../../shared/modules/pi/extensions/directory-agents-md.ts} "$agentDir/extensions/directory-agents-md.ts"
        '';

        # GitHub's ed25519 host key, pinned so the backup push never needs a TOFU prompt.
        knownHosts = pkgs.writeText "apollo-known-hosts" ''
          github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
        '';

        # Provision the workspace repo + install the per-repo deploy keys (workspace backup +
        # obsidian vault) and clone the vault. Shared by the app and the backup unit (both run as the
        # apollo user). The private keys land in the world-readable /nix/store, an accepted trade-off
        # on this single-purpose VM (as with trader's wallet key); each is a read-write deploy key
        # scoped to its one private repo.
        gitBootstrap = pkgs.writeShellScript "apollo-git-bootstrap" ''
          set -euo pipefail
          export PATH=${lib.makeBinPath gitPkgs}:$PATH

          install -d -m 700 "$HOME/.ssh"
          install -m 600 ${pkgs.writeText "apollo-ssh-key" secrets.git.workspace.sshKey} "$HOME/.ssh/id_apollo"
          install -m 600 ${pkgs.writeText "apollo-obsidian-key" secrets.git.obsidian.sshKey} "$HOME/.ssh/id_obsidian"
          install -m 644 ${knownHosts} "$HOME/.ssh/known_hosts"

          mkdir -p "$APOLLO_WORKSPACE"
          if [ ! -e "$APOLLO_WORKSPACE/.git" ]; then
            git -C "$APOLLO_WORKSPACE" init -b main
          fi
          git -C "$APOLLO_WORKSPACE" remote add origin "${secrets.git.workspace.remote}" 2>/dev/null \
            || git -C "$APOLLO_WORKSPACE" remote set-url origin "${secrets.git.workspace.remote}"

          # The obsidian vault is a nested git repo; keep it out of the workspace backup.
          touch "$APOLLO_WORKSPACE/.git/info/exclude"
          grep -qxF "obsidian/" "$APOLLO_WORKSPACE/.git/info/exclude" \
            || echo "obsidian/" >> "$APOLLO_WORKSPACE/.git/info/exclude"

          # Obsidian vault: a separate repo, cloned here so it always exists and kept
          # out of the workspace backup (above). Configured with the deploy key and the
          # user's identity, which is what lets the obsidian skill commit, pull and push
          # it (that skill owns every git command against the vault; the agent runs none
          # itself). Best-effort: a clone failure (e.g. no network at boot) must not
          # block startup.
          obsidianSsh="ssh -i $HOME/.ssh/id_obsidian -o IdentitiesOnly=yes -o UserKnownHostsFile=$HOME/.ssh/known_hosts -o StrictHostKeyChecking=yes"
          if [ ! -e "$APOLLO_WORKSPACE/obsidian/.git" ]; then
            GIT_SSH_COMMAND="$obsidianSsh" git clone "${secrets.git.obsidian.remote}" "$APOLLO_WORKSPACE/obsidian" || true
          fi
          if [ -e "$APOLLO_WORKSPACE/obsidian/.git" ]; then
            git -C "$APOLLO_WORKSPACE/obsidian" config core.sshCommand "$obsidianSsh"
            git -C "$APOLLO_WORKSPACE/obsidian" config user.name Roman
            git -C "$APOLLO_WORKSPACE/obsidian" config user.email roman@lerchster.dev
          fi
        '';

        # The workspace backup itself: commit everything and push, printing the one-line outcome. It
        # runs server-side only - by the 3h timer (apollo-backup.service) and, on demand, spawned by
        # the app from /internal/backup. The agent triggers it over HTTP and relays the outcome; the
        # backup skill never runs git itself.
        workspaceBackupScript = pkgs.writeShellApplication {
          name = "apollo-workspace-backup";
          runtimeInputs = with pkgs; [
            coreutils
            git
            openssh
          ];
          text = ''
            export GIT_AUTHOR_NAME=Roman GIT_COMMITTER_NAME=Roman
            export GIT_AUTHOR_EMAIL=roman@lerchster.dev GIT_COMMITTER_EMAIL=roman@lerchster.dev
            export GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=safe.directory GIT_CONFIG_VALUE_0='*'
            export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/id_apollo -o IdentitiesOnly=yes -o UserKnownHostsFile=$HOME/.ssh/known_hosts -o StrictHostKeyChecking=yes"

            cd "''${APOLLO_WORKSPACE:-/var/lib/apollo/workspace}"
            git add -A
            if git diff --cached --quiet; then
              echo "Nothing to back up."
            else
              git commit -q -m "$(date '+%Y-%m-%d %H:%M:%S')"
              git push -q -u origin main
              echo "Backed up and pushed."
            fi
          '';
        };

        # The Proton account password, handed to `account login` as a file rather
        # than through argv or the environment, neither of which can hold a secret
        # (same world-readable /nix/store trade-off as the git deploy keys above).
        protonPassword = pkgs.writeText "apollo-proton-password" (secrets.proton.password or "");

        # An account reaches proton through `account login`, which saves a session
        # under $HOME. Signing in again with a live session only resumes it, so a unit
        # can do this before its real work and recover on its own from a session that
        # expired or was revoked.
        protonLogin = ''
          ${protonCli}/bin/proton account login --quiet \
            --user ${secrets.proton.user or ""} --password-file %d/proton-password'';

        protonCredential = "proton-password:${protonPassword}";

        # Written once a run has fully succeeded, and read by the job itself to tell an
        # hour that still owes the day's copy from one that does not.
        dbBackupStatus = "/var/lib/apollo-db-backup/status.json";

        dbBackupDue = import ../../backup-due.nix { inherit pkgs; } {
          name = "apollo-db-backup";
          statusFile = dbBackupStatus;
        };

        # The day's off-box copy of Apollo's SQLite DB to Proton Drive (mirrors the
        # trader VM): online-snapshot the live DB, zstd-compress, upload, keep the
        # newest N. Runs as root to read the apollo-owned DB. Restore: download a
        # *.sqlite.zst, `zstd -d` it, stop apollo.service, drop it in as
        # /var/lib/apollo/apollo.sqlite (chown apollo:apollo, delete any -wal/-shm),
        # start.
        dbBackupScript = pkgs.writeShellApplication {
          name = "apollo-db-backup";
          runtimeInputs = [
            protonCli
          ]
          ++ (with pkgs; [
            coreutils
            jq
            sqlite
            zstd
          ]);
          text = ''
            src=/var/lib/apollo/apollo.sqlite
            remote="/backups/apollo"
            keep=8

            ts="$(date --utc +%Y-%m-%dT%H-%M-%SZ)"
            work="$(mktemp --directory "$HOME/backup.XXXXXX")"
            trap 'rm --recursive --force "$work"' EXIT

            # Exit 3 is "no such path". Anything else (network, auth) is a real
            # failure, and answering it by creating a folder that already exists
            # would only trade it for a confusing one. `items create` makes the
            # folders above its path too, so the leaf is the whole request.
            ensure_folder() {
              local path="$1" status=0
              proton drive items get "$path" >/dev/null 2>&1 || status=$?
              case "$status" in
                0) ;;
                3) proton drive items create "$path" >/dev/null ;;
                *) echo "cannot reach Drive ($path, exit $status)" >&2; exit "$status" ;;
              esac
            }

            snap="$work/apollo.sqlite"
            comp="$work/apollo-$ts.sqlite.zst"
            # The app holds the DB open (live -shm), so the online-backup API takes a
            # consistent, up-to-the-last-commit snapshot without blocking it.
            echo "snapshotting $src"
            sqlite3 -bail -readonly "$src" ".timeout 5000" ".backup $snap"
            [ -s "$snap" ] || { echo "snapshot is empty: $src" >&2; exit 1; }
            zstd --quiet --threads=0 --force -o "$comp" "$snap"

            ensure_folder "$remote"
            echo "uploading $(basename "$comp") ($(stat --format=%s "$comp") bytes)"
            proton drive items upload "$comp" "$remote"

            # Newest-first by name (UTC timestamps sort lexicographically); keep the
            # newest $keep, delete the rest in one call. Runs only after the upload
            # succeeds. --page-size 0 is the whole folder; a listing is otherwise
            # the first 50 of it.
            stale="$(
              proton drive items list "$remote" --output json --page-size 0 \
                | jq --raw-output '[.items[].name | select(startswith("apollo-"))] | sort | reverse | .[]' \
                | tail --lines=+$((keep + 1))
            )"
            if [ -n "$stale" ]; then
              paths=()
              while IFS= read -r name; do
                echo "pruning $name"
                paths+=("$remote/$name")
              done <<<"$stale"
              proton drive items delete --yes "''${paths[@]}"
            fi

            # The heartbeat is written last and only here, so a run that died anywhere
            # above still owes the day's copy and the next hour takes it. Renamed into
            # place so a reader never sees a half-written file.
            jq --null-input --compact-output \
              --arg ts "$(date --utc --iso-8601=seconds)" \
              --argjson bytes "$(stat --format=%s "$comp")" \
              '{ts: $ts, bytes: $bytes}' >"$work/status.json"
            mv "$work/status.json" ${dbBackupStatus}
            echo "backup complete"
          '';
        };

        # Scheduled jobs: a command run as the apollo user on a calendar schedule, with the
        # workspace and the app's localhost hook in reach. A schedule is infrastructure, so it
        # belongs here; what a job acts on (the watched products, the postcode, the coordinates) is
        # user data and lives in the workspace, where the agent can change it without a redeploy.
        # Adding another job is one attribute below - its service and timer are derived from it.
        #
        # A job speaks to the user by POSTing to /internal/skill-message, exactly as the skills do
        # when the agent runs them, and stays silent by printing nothing. A non-zero exit is logged
        # at error by systemd and surfaces on WhatsApp through the app's own warn+ forwarding.
        scheduledJobs = {
          briefing = {
            description = "Send the day's briefing: sky, calendar and offers";
            # The composer owns no data: it asks the weather and offers skills for their text, so it
            # needs their scripts by path - siblings do not exist between store paths.
            environment = {
              APOLLO_OFFERS_SCRIPT = "${./agent/skills/offers/scripts/offers.py}";
              APOLLO_WEATHER_SCRIPT = "${./agent/skills/weather/scripts/weather.py}";
            };
            exec = "${./agent/skills/briefing/scripts/briefing.py} show";
            onCalendar = "*-*-* 08:00:00";
            packages = [
              pkgs.python3
              protonCli
            ];
            # HOME is the app's state directory, so this keeps the session the agent
            # uses alive as much as it serves the briefing's own calendar read.
            protonSession = true;
          };
        };

        # A job exists to say something to the user, so it has nothing to do until the
        # app can carry it. The catch-up run of a missed schedule lands seconds after
        # boot, well before WhatsApp has linked, and delivery then fails - so this
        # waits, and if the app never becomes able to deliver, the run is skipped
        # rather than failed. ExecCondition is what draws that distinction: a job that
        # had nothing to say is not a fault worth waking anyone for.
        deliverable = pkgs.writeShellApplication {
          name = "apollo-deliverable";
          runtimeInputs = [ pkgs.curl ];
          text = ''
            for _ in $(seq 60); do
              curl --silent --fail --max-time 5 "http://127.0.0.1:${toString port}/health" >/dev/null && exit 0
              sleep 2
            done
            echo "the app cannot deliver messages; skipping this run"
            exit 1
          '';
        };

        jobService = _name: job: {
          inherit (job) description;

          after = [ "network-online.target" ];
          wants = [ "network-online.target" ];

          environment = {
            # A job runs from the state directory, not the workspace, so the skill scripts it
            # invokes are told where the user's data is rather than left to infer it.
            APOLLO_WORKSPACE = "%S/apollo/workspace";
            HOME = "%S/apollo";
            PORT = toString port;
            SSL_CERT_FILE = "/etc/ssl/certs/ca-certificates.crt";
          }
          // lib.optionalAttrs (job.protonSession or false) { PROTON_NO_INPUT = "1"; }
          // (job.environment or { });

          path = job.packages or [ ];

          serviceConfig = {
            ExecCondition = lib.getExe deliverable;
            ExecStart = job.exec;
            Group = "apollo";
            NoNewPrivileges = true;
            PrivateTmp = true;
            StateDirectory = "apollo";
            Type = "oneshot";
            User = "apollo";
            WorkingDirectory = "%S/apollo";
          }
          // lib.optionalAttrs (job.protonSession or false) {
            # Leading "-": a job does more than talk to Proton, so an unreachable
            # Proton costs it that part of its work rather than the whole run.
            ExecStartPre = "-${protonLogin}";
            LoadCredential = protonCredential;
          };
        };

        # Persistent, so a schedule missed while the VM was down runs once on the next boot
        # rather than being skipped for the day.
        jobTimer = name: job: {
          description = "Schedule for apollo-${name}";

          timerConfig = {
            OnCalendar = job.onCalendar;
            Persistent = true;
          };

          wantedBy = [ "timers.target" ];
        };

        jobUnits =
          make: lib.mapAttrs' (name: job: lib.nameValuePair "apollo-${name}" (make name job)) scheduledJobs;

      in
      {
        imports = [ { systemd = checks.pushUnits "apollo"; } ];

        microvm = {
          hypervisor = "qemu";
          mem = 4096;
          vcpu = 2;

          interfaces = [
            {
              id = "vm-apollo";
              mac = "52:54:00:3e:a2:c3";
              type = "tap";
            }
          ];

          shares = [
            {
              mountPoint = "/nix/.ro-store";
              proto = "virtiofs";
              source = "/nix/store";
              tag = "ro-store";
            }
          ];

          volumes = [
            {
              image = "var.img";
              mountPoint = "/var";
              size = 40960;
            }
          ];
        };

        environment.systemPackages = with pkgs; [
          bun
          curl
          git
          jq
          ripgrep
        ];

        # Chromium carries no fonts of its own and NixOS installs none by default, so without these
        # every label in a rendered diagram (and every screenshot the browser skill takes) comes out
        # as a row of empty boxes.
        fonts.packages = with pkgs; [
          dejavu_fonts
          liberation_ttf
          noto-fonts-color-emoji
        ];

        networking = {
          firewall.allowedTCPPorts = [ port ];
          hostName = "apollo";
          useNetworkd = true;
        };

        security.sudo.wheelNeedsPassword = false;

        services = {
          beszel.agent = {
            enable = true;
            environment.KEY = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILRp6cIsh8pO+LF+s1qe1Zl5v/sZWlR23GcCow7g6D7L";
            openFirewall = true;
          };

          openssh = {
            enable = true;

            hostKeys = [
              {
                path = "/var/lib/ssh-host-keys/ssh_host_ed25519_key";
                type = "ed25519";
              }
              {
                path = "/var/lib/ssh-host-keys/ssh_host_rsa_key";
                type = "rsa";
              }
            ];

            settings.PermitRootLogin = "yes";
          };
        };

        system.stateVersion = "26.05";

        systemd = {
          network = {
            enable = true;

            networks."20-lan" = {
              matchConfig.Type = "ether";
              networkConfig.DHCP = "yes";
            };
          };

          services = {
            apollo = {
              description = "Apollo WhatsApp assistant (pi SDK + Baileys)";

              after = [ "network-online.target" ];
              requires = [ "network-online.target" ];
              wantedBy = [ "multi-user.target" ];

              environment = {
                APOLLO_ALLOW_FROM = secrets.mainNumber;
                APOLLO_BACKUP_SCRIPT = lib.getExe workspaceBackupScript;
                # Where the user renews credentials only they can renew; named in the WhatsApp
                # notice that tells them to, since that message is Apollo's only way to ask.
                APOLLO_DASHBOARD_URL = "https://apollo.halerc.xyz";
                APOLLO_DB_PATH = "%S/apollo/apollo.sqlite";
                # Where a file the user sends lands: beside the database, so it is neither
                # committed to the workspace repo nor carried into the nightly database backup.
                APOLLO_FILE_DIR = "%S/apollo/files";
                APOLLO_MODEL = "openrouter/deepseek/deepseek-v4-flash-vision-exp";
                APOLLO_PROFILE_PICTURE = "${profilePicture}";
                APOLLO_THINKING = "xhigh";
                APOLLO_WORKSPACE = "%S/apollo/workspace";
                # The browser skill runs `browse` via bunx (`bunx --bun browse@latest`). bunx
                # caches the download under BUN_INSTALL_CACHE_DIR and stages the runnable tree
                # under $TMPDIR; pointing the cache at the service's own PrivateTmp /tmp keeps the
                # whole exec surface on one exec-capable filesystem so a native prebuild (e.g.
                # bufferutil) never hits "Permission denied". It's ephemeral, so the first browse
                # after a restart re-downloads (~50s, within the tool timeout). No ignore-scripts
                # flag is needed: bun does not run dependencies' lifecycle scripts by default, and
                # browse's natives ship prebuilt (bufferutil) or as platform packages (esbuild), so
                # nothing compiles.
                BUN_INSTALL_CACHE_DIR = "/tmp/bun-cache";
                CHROME_PATH = "${chromeWrapper}";
                HOME = "%S/apollo";
                MISTRAL_API_KEY = secrets.mistralApiKey;
                # Opt pi into the provider's 1h prompt-cache TTL (default is 5min). The assistant is
                # messaged in bursts separated by idle gaps, so a return within the hour reuses the
                # cached conversation (cheap cache reads) instead of re-priming the whole prefix
                # (expensive cache writes) as a 5min cache would after every gap.
                PI_CACHE_RETENTION = "long";
                PORT = toString port;
                # A missing credential or an unanswerable question becomes an error
                # instead of a prompt nobody is there to see.
                PROTON_NO_INPUT = "1";
                SSL_CERT_FILE = "/etc/ssl/certs/ca-certificates.crt";
              };

              # writeBunApplication's runtimeInputs only populate the build
              # closure, not the unit's PATH, so the tools the agent shells out
              # to (incl. python3 for the macros skill) are added here.
              path = agentPkgs;

              serviceConfig = {
                ExecStart = "${apolloApp}/bin/apollo";
                # Leading "-": Proton is one of the agent's capabilities, not its
                # reason to exist, so an unreachable Proton must not keep the
                # assistant off WhatsApp.
                ExecStartPre = [
                  setup
                  gitBootstrap
                  "-${protonLogin}"
                ];
                Group = "apollo";
                LoadCredential = protonCredential;
                PrivateTmp = true;
                RemoveIPC = true;
                Restart = "on-failure";
                RestartSec = "10s";
                StateDirectory = "apollo";
                # Shared identity with apollo-backup so the timer pushes the
                # workspace as the same user that owns it.
                User = "apollo";
                WorkingDirectory = "%S/apollo";
              };
            };

            # Scheduled workspace backup (the 3h timer starts it). Runs the shared backup script as
            # the apollo user; the app runs the same script on demand from /internal/backup.
            apollo-backup = {
              description = "Back up the Apollo workspace to git";

              after = [ "network-online.target" ];
              wants = [ "network-online.target" ];

              environment = {
                APOLLO_WORKSPACE = "%S/apollo/workspace";
                HOME = "%S/apollo";
                SSL_CERT_FILE = "/etc/ssl/certs/ca-certificates.crt";
              };

              path = gitPkgs;

              onFailure = [ "${checks.failureUnitName checks.registry.apollo-workspace-backup}.service" ];

              serviceConfig = {
                ExecStart = lib.getExe workspaceBackupScript;
                ExecStartPost = checks.pushSuccess checks.registry.apollo-workspace-backup;
                ExecStartPre = gitBootstrap;
                Group = "apollo";
                StateDirectory = "apollo";
                Type = "oneshot";
                User = "apollo";
                WorkingDirectory = "%S/apollo";
              };
            };

            # Runs as root (no DynamicUser) so it can read the apollo-owned DB; its
            # own StateDirectory doubles as proton's HOME for the session cache and
            # holds the heartbeat.
            #
            # The timer asks once an hour through the quiet hours and ExecCondition
            # answers, so the hour that finds the day's copy already taken skips without
            # pushing or paging anything, and a Proton that answered with a bad gateway
            # at 01:00 costs an hour rather than the day. A page therefore means all
            # four attempts failed.
            apollo-db-backup = {
              description = "Back up the Apollo SQLite database to Proton Drive";

              after = [ "network-online.target" ];
              onFailure = [ "${checks.failureUnitName checks.registry.apollo-db-backup}.service" ];
              wants = [ "network-online.target" ];

              environment = {
                HOME = "%S/apollo-db-backup";
                PROTON_NO_INPUT = "1";
              };

              serviceConfig = {
                ExecCondition = lib.getExe dbBackupDue;
                ExecStart = lib.getExe dbBackupScript;
                ExecStartPost = checks.pushSuccess checks.registry.apollo-db-backup;
                # This unit exists to talk to Proton, so a sign-in it cannot complete
                # ends the run here rather than at the first Drive call.
                ExecStartPre = protonLogin;
                LoadCredential = protonCredential;
                StateDirectory = "apollo-db-backup";
                StateDirectoryMode = "0700";
                TimeoutStartSec = "1800s";
                Type = "oneshot";

                NoNewPrivileges = true;
                PrivateTmp = true;
                ProtectHome = true;
                ProtectSystem = "strict";
                RestrictAddressFamilies = [
                  "AF_INET"
                  "AF_INET6"
                  "AF_UNIX"
                ];
              };
            };

          }
          // jobUnits jobService;

          timers = {
            apollo-backup = {
              description = "Back up the Apollo workspace every 3 hours";

              timerConfig = {
                OnCalendar = "*-*-* 00/03:00:00";
                Persistent = true;
              };

              wantedBy = [ "timers.target" ];
            };

            apollo-db-backup = {
              description = "Ask hourly from 01:00 whether the day's database backup is owed";

              timerConfig = {
                OnCalendar = "*-*-* 01,02,03,04:00:00";
                # A guest that was down over an attempt asks the moment it is up, rather
                # than waiting out the rest of the window.
                Persistent = true;
              };

              wantedBy = [ "timers.target" ];
            };
          }
          // jobUnits jobTimer;
        };

        time.timeZone = "Europe/Vienna";

        users.groups.apollo.gid = 970;

        users.users.apollo = {
          description = "Apollo WhatsApp assistant";
          group = "apollo";
          home = "/var/lib/apollo";
          isSystemUser = true;
          uid = 970;
        };

        users.users.roman = {
          extraGroups = [ "wheel" ];
          isNormalUser = true;
          openssh.authorizedKeys.keys = [
            "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC2UfiONg3o2mydlSFdpIRWD9lRc+F/QK2GtHJPe3hYADJMFq+59gpYpuzA8Ccya6wGxkSUgcAWP5rqbidfsD08NzxQgCGz2HWyD0if0FkM2eeqOlOuJ5ymJ7NWnF1AQQBNE27UIPUW+beTlDCZEUZubSSfe87PEKbYgTeV7bO4BlXOzO+JI4AqUEuxQ5T6oFpUtKt+SepslsMECJZQnTBJBAITXBaBTwJwHYdNYx5WeK8+ObILPgapA0/l1/5y+zXBrU4ZH4xMSmlFNnt9iQxikrVXlWJvmieDfyPmkJSCJblqnhEmEgIyi+w/iPH5IwXaX8dwfp2mLM3ULSC5XvRPX7Pqs9gRmYAlaaFB7NEG2sEr8pWSq0Ag4enILp1otEvCLJtc/pbNa60rXiLpioOQ3kgsoMizsOHzqR7CN834dH3AK49zSKjEFVZLugzrB/GTsNH04+oQXbuDW04ok4b7xdy7fMPIA3I6TkaSHDfWAQ3DqaYdtmRzqlH3iljpVrTF6Mkjwuw8GZskblpx7AJXT7iH3CGXOVIf/qJnk806eDGKFwKLT/Pr86crmxbGdqiMIIM6UJ+0Ka+MMgaRrwi6h9FIRNUL6QM7/zC0QwNBxdGYtSOx58Z0qZ/LGqwm1qel2w0WIOkirbxLvk4Rbo+HedAZ8K38z9B7ZcCiN/U7bQ== roman@lerchster.dev"
          ];
        };
      };
  };
}
