{ inputs, ... }:
let
  system = "x86_64-linux";

  pkgs = import inputs.nixpkgs {
    inherit system;
    overlays = [ inputs.bun2nix.overlays.default ];
  };

  # Tool sets shared across the app and the systemd units, defined once here.
  # agentPkgs: everything the agent shells out to. gitPkgs: what the git backup
  # and bootstrap scripts need. (Guest units reference these host-eval lists,
  # as they already do for apolloApp.)
  agentPkgs =
    (with pkgs; [
      bash
      coreutils
      curl
      ffmpeg-headless
      git
      gnugrep
      gnused
      jq
      nodejs
      openssh
      poppler-utils
      python3
      ripgrep
      tesseract
    ])
    ++ [ inputs.proton-cli.packages.${system}.default ];
  gitPkgs = with pkgs; [
    bash
    coreutils
    git
    openssh
  ];

  # Reproducible build: node_modules + web assets are built on the Nix builder
  # (bun.nix is generated by `bunx bun2nix -o bun.nix`), so nothing is installed
  # or compiled on the VM at runtime.
  apolloApp = pkgs.bun2nix.writeBunApplication {
    pname = "apollo";
    version = "1.0.0";

    src = ./.;

    bunDeps = pkgs.bun2nix.fetchBunDeps { bunNix = ./bun.nix; };

    # Tailwind's native engine (oxide) needs libstdc++/libgcc while building the
    # CSS. autoPatchElf is avoided because sharp ships musl-libc variants that
    # cannot be patched on glibc; sharp is an optional baileys dependency that
    # is never exercised here (Apollo only receives images), so its unpatched
    # natives are harmless at runtime.
    buildPhase = ''
      export LD_LIBRARY_PATH=${pkgs.lib.makeLibraryPath [ pkgs.stdenv.cc.cc.lib ]}
      bun run build:web
    '';
    dontUseBunCheck = true;
    startScript = "bun run src/index.ts";

    runtimeInputs = agentPkgs;
  };
in
{
  microvm.vms.apollo = {
    autostart = true;

    config =
      { lib, pkgs, ... }:
      let
        port = 8080;

        secrets = builtins.fromJSON (builtins.readFile ./secrets.json);

        # Chromium for the browser skill's managed-local sessions. chrome-launcher (inside
        # `browse`) picks it up via CHROME_PATH; the flags are the standard headless-in-a-VM
        # pair - no user-namespace sandbox, and no reliance on a large /dev/shm.
        chromeWrapper = pkgs.writeShellScript "apollo-chrome" ''
          exec ${pkgs.chromium}/bin/chromium --no-sandbox --disable-dev-shm-usage "$@"
        '';

        setup = pkgs.writeShellScript "apollo-setup" ''
          set -euo pipefail
          export PATH=${lib.makeBinPath [ pkgs.coreutils ]}:$PATH

          agentDir="$HOME/.pi/agent"
          mkdir -p "$agentDir/sessions" "$agentDir/skills" "$agentDir/extensions" "$HOME/whatsapp"

          # SYSTEM_PROMPT.md is the agent's system prompt
          ln -sfn ${./agent/SYSTEM_PROMPT.md} "$agentDir/SYSTEM_PROMPT.md"

          # COMPACTION_PROMPT.md overrides how the session is summarized on compaction
          ln -sfn ${./agent/COMPACTION_PROMPT.md} "$agentDir/COMPACTION_PROMPT.md"

          # Skills pi discovers from $agentDir/skills (read-only)
          ln -sfn ${../../../../shared/modules/pi/skills/browser} "$agentDir/skills/browser"
          ln -sfn ${../../../../shared/modules/pi/skills/context7} "$agentDir/skills/context7"
          ln -sfn ${../../../../shared/modules/pi/skills/exa} "$agentDir/skills/exa"
          ln -sfn ${./agent/skills/backup} "$agentDir/skills/backup"
          ln -sfn ${./agent/skills/macros} "$agentDir/skills/macros"
          ln -sfn ${./agent/skills/proton} "$agentDir/skills/proton"
          ln -sfn ${./agent/skills/reminders} "$agentDir/skills/reminders"

          # Extensions pi discovers from $agentDir/extensions. directory-agents-md
          # injects each vault folder's AGENTS.md on read/write/edit.
          ln -sfn ${../../../../shared/modules/pi/extensions/directory-agents-md.ts} "$agentDir/extensions/directory-agents-md.ts"
        '';

        # GitHub's ed25519 host key, pinned so the backup push never needs a TOFU prompt.
        knownHosts = pkgs.writeText "apollo-known-hosts" ''
          github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
        '';

        # Provision the workspace repo + install the per-repo deploy keys (workspace
        # backup + obsidian vault). Shared by the app and the backup timer (both run
        # as the "apollo" dynamic user, so they see the same $HOME and workspace). The
        # private keys land in the world-readable /nix/store, an accepted trade-off on
        # this single-purpose VM (as with trader's wallet key); each is a read-write
        # deploy key scoped to its one private repo.
        gitBootstrap = pkgs.writeShellScript "apollo-git-bootstrap" ''
          set -euo pipefail
          export PATH=${lib.makeBinPath gitPkgs}:$PATH

          install -d -m 700 "$HOME/.ssh"
          install -m 600 ${pkgs.writeText "apollo-ssh-key" secrets.git.workspace.sshKey} "$HOME/.ssh/id_apollo"
          install -m 600 ${pkgs.writeText "apollo-obsidian-key" secrets.git.obsidian.sshKey} "$HOME/.ssh/id_obsidian"
          install -m 644 ${knownHosts} "$HOME/.ssh/known_hosts"

          mkdir -p "$APOLLO_WORKSPACE"
          if [ ! -e "$APOLLO_WORKSPACE/.git" ]; then
            git -C "$APOLLO_WORKSPACE" init -b main
          fi
          git -C "$APOLLO_WORKSPACE" remote add origin "${secrets.git.workspace.remote}" 2>/dev/null \
            || git -C "$APOLLO_WORKSPACE" remote set-url origin "${secrets.git.workspace.remote}"

          # The obsidian vault is a nested git repo; keep it out of the workspace backup.
          touch "$APOLLO_WORKSPACE/.git/info/exclude"
          grep -qxF "obsidian/" "$APOLLO_WORKSPACE/.git/info/exclude" \
            || echo "obsidian/" >> "$APOLLO_WORKSPACE/.git/info/exclude"

          # Obsidian vault: a separate repo, cloned here so it always exists and kept
          # out of the workspace backup (above). Configured with the deploy key and
          # the user's identity so the agent syncs it with plain `git -C .../obsidian ...`
          # commands (documented in the vault's own AGENTS.md). Best-effort: a clone
          # failure (e.g. no network at boot) must not block startup.
          obsidianSsh="ssh -i $HOME/.ssh/id_obsidian -o IdentitiesOnly=yes -o UserKnownHostsFile=$HOME/.ssh/known_hosts -o StrictHostKeyChecking=yes"
          if [ ! -e "$APOLLO_WORKSPACE/obsidian/.git" ]; then
            GIT_SSH_COMMAND="$obsidianSsh" git clone "${secrets.git.obsidian.remote}" "$APOLLO_WORKSPACE/obsidian" || true
          fi
          if [ -e "$APOLLO_WORKSPACE/obsidian/.git" ]; then
            git -C "$APOLLO_WORKSPACE/obsidian" config core.sshCommand "$obsidianSsh"
            git -C "$APOLLO_WORKSPACE/obsidian" config user.name Roman
            git -C "$APOLLO_WORKSPACE/obsidian" config user.email roman@lerchster.dev
          fi
        '';

        # Proton credentials, consumed as the unit EnvironmentFile by both the app
        # (so the agent's proton-cli is authenticated) and the SQLite backup job (same
        # world-readable /nix/store trade-off as the git deploy keys above).
        protonEnv = pkgs.writeText "apollo-proton-env" ''
          PROTON_USER=${secrets.proton.user or ""}
          PROTON_PASSWORD=${secrets.proton.password or ""}
        '';

        # Nightly off-box backup of Apollo's SQLite DB to Proton Drive (mirrors the
        # trader VM): online-snapshot the live DB, zstd-compress, upload, keep the
        # newest N. Runs as root to read the apollo-owned DB; Proton creds come from
        # the unit EnvironmentFile. Restore: download a *.sqlite.zst, `zstd -d` it,
        # stop apollo.service, drop it in as /var/lib/apollo/apollo.sqlite (chown
        # apollo:apollo, delete any -wal/-shm), start.
        dbBackupScript = pkgs.writeShellApplication {
          name = "apollo-db-backup";
          runtimeInputs = [
            inputs.proton-cli.packages.${pkgs.stdenv.hostPlatform.system}.default
          ]
          ++ (with pkgs; [
            coreutils
            jq
            sqlite
            zstd
          ]);
          text = ''
            src=/var/lib/apollo/apollo.sqlite
            remote_parent="/backups"
            remote="/backups/apollo"
            keep=8

            ts="$(date --utc +%Y-%m-%dT%H-%M-%SZ)"
            work="$(mktemp --directory "$HOME/backup.XXXXXX")"
            trap 'rm --recursive --force "$work"' EXIT

            ensure_folder() {
              local path="$1"
              proton-cli drive items info "$path" >/dev/null 2>&1 && return 0
              proton-cli drive folders create "$path" >/dev/null
            }

            snap="$work/apollo.sqlite"
            comp="$work/apollo-$ts.sqlite.zst"
            # The app holds the DB open (live -shm), so the online-backup API takes a
            # consistent, up-to-the-last-commit snapshot without blocking it.
            echo "snapshotting $src"
            sqlite3 -bail -readonly "$src" ".timeout 5000" ".backup $snap"
            [ -s "$snap" ] || { echo "snapshot is empty: $src" >&2; exit 1; }
            zstd --quiet --threads=0 --force -o "$comp" "$snap"

            ensure_folder "$remote_parent"
            ensure_folder "$remote"
            echo "uploading $(basename "$comp") ($(stat --format=%s "$comp") bytes)"
            proton-cli drive items upload "$comp" "$remote"

            # Newest-first by name (UTC timestamps sort lexicographically); keep the
            # newest $keep, delete the rest. Runs only after the upload succeeds.
            proton-cli drive items list "$remote" --output json \
              | jq --raw-output '[.[] | select(.name | startswith("apollo-")) | .name] | sort | reverse | .[]' \
              | tail --lines=+$((keep + 1)) \
              | while IFS= read -r name; do
                  echo "pruning $name"
                  proton-cli drive items delete "$remote/$name"
                done
            echo "backup complete"
          '';
        };

        # signal-cli has no place here, so a failed backup pings the user over the same
        # WhatsApp channel the app already owns: curl the app's localhost-only alert
        # hook (src/index.ts), wired as the backup unit's OnFailure below.
        dbBackupAlertScript = pkgs.writeShellApplication {
          name = "apollo-db-backup-alert";
          runtimeInputs = [ pkgs.curl ];
          text = ''
            curl --silent --show-error --fail --max-time 30 \
              --request POST "http://127.0.0.1:${toString port}/internal/backup-alert"
          '';
        };

      in
      {
        microvm = {
          hypervisor = "qemu";
          mem = 4096;
          vcpu = 2;

          interfaces = [
            {
              id = "vm-apollo";
              mac = "52:54:00:3e:a2:c3";
              type = "tap";
            }
          ];

          shares = [
            {
              mountPoint = "/nix/.ro-store";
              proto = "virtiofs";
              source = "/nix/store";
              tag = "ro-store";
            }
          ];

          volumes = [
            {
              image = "var.img";
              mountPoint = "/var";
              size = 40960;
            }
          ];
        };

        environment.systemPackages = with pkgs; [
          bun
          curl
          git
          jq
          ripgrep
        ];

        networking = {
          firewall.allowedTCPPorts = [ port ];
          hostName = "apollo";
          useNetworkd = true;
        };

        security.sudo.wheelNeedsPassword = false;

        services = {
          beszel.agent = {
            enable = true;
            environment.KEY = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILRp6cIsh8pO+LF+s1qe1Zl5v/sZWlR23GcCow7g6D7L";
            openFirewall = true;
          };

          openssh = {
            enable = true;

            hostKeys = [
              {
                path = "/var/lib/ssh-host-keys/ssh_host_ed25519_key";
                type = "ed25519";
              }
              {
                path = "/var/lib/ssh-host-keys/ssh_host_rsa_key";
                type = "rsa";
              }
            ];

            settings.PermitRootLogin = "yes";
          };
        };

        system.stateVersion = "26.05";

        systemd = {
          network = {
            enable = true;

            networks."20-lan" = {
              matchConfig.Type = "ether";
              networkConfig.DHCP = "yes";
            };
          };

          services = {
            apollo = {
              description = "Apollo WhatsApp assistant (pi SDK + Baileys)";

              after = [ "network-online.target" ];
              requires = [ "network-online.target" ];
              wantedBy = [ "multi-user.target" ];

              environment = {
                APOLLO_ALLOW_FROM = secrets.mainNumber;
                APOLLO_DB_PATH = "%S/apollo/apollo.sqlite";
                APOLLO_MODEL = "anthropic/claude-sonnet-5";
                APOLLO_THINKING = "high";
                APOLLO_WORKSPACE = "%S/apollo/workspace";
                CHROME_PATH = "${chromeWrapper}";
                HOME = "%S/apollo";
                MISTRAL_API_KEY = secrets.mistralApiKey;
                # The browser skill runs via npx, which installs and *exec*s its package from the
                # npm cache. HOME (the DynamicUser StateDirectory) is a noexec mount, so put the
                # cache on the service's exec /tmp - otherwise the browse binary (and the deps'
                # install-script binaries) hit "Permission denied" (exit 126). It's ephemeral, so
                # the first browse after a restart re-installs (~50s, within the tool timeout).
                # Skipping install scripts keeps that install clean (esbuild's binary is static,
                # bufferutil an optional ws speedup ws falls back from).
                NPM_CONFIG_CACHE = "/tmp/npm";
                NPM_CONFIG_IGNORE_SCRIPTS = "true";
                PORT = toString port;
                SSL_CERT_FILE = "/etc/ssl/certs/ca-certificates.crt";
              };

              # writeBunApplication's runtimeInputs only populate the build
              # closure, not the unit's PATH, so the tools the agent shells out
              # to (incl. python3 for the macros skill) are added here.
              path = agentPkgs;

              serviceConfig = {
                DynamicUser = true;
                EnvironmentFile = protonEnv;
                ExecStart = "${apolloApp}/bin/apollo";
                ExecStartPre = [
                  setup
                  gitBootstrap
                ];
                Restart = "on-failure";
                RestartSec = "10s";
                StateDirectory = "apollo";
                # Shared identity with apollo-backup so the timer pushes the
                # workspace as the same user that owns it.
                User = "apollo";
                WorkingDirectory = "%S/apollo";
              };
            };

            apollo-backup = {
              description = "Back up the Apollo workspace to git";

              after = [ "network-online.target" ];
              wants = [ "network-online.target" ];

              environment = {
                APOLLO_WORKSPACE = "%S/apollo/workspace";
                HOME = "%S/apollo";
                SSL_CERT_FILE = "/etc/ssl/certs/ca-certificates.crt";
              };

              path = gitPkgs;

              serviceConfig = {
                DynamicUser = true;
                ExecStart = "${./agent/skills/backup}/scripts/backup.sh";
                ExecStartPre = gitBootstrap;
                StateDirectory = "apollo";
                Type = "oneshot";
                User = "apollo";
                WorkingDirectory = "%S/apollo";
              };
            };

            # Runs as root (no DynamicUser) so it can read the apollo-owned DB; its
            # own StateDirectory doubles as proton-cli's HOME for the session cache.
            apollo-db-backup = {
              description = "Back up the Apollo SQLite database to Proton Drive";

              after = [ "network-online.target" ];
              onFailure = [ "apollo-db-backup-alert.service" ];
              wants = [ "network-online.target" ];

              environment.HOME = "%S/apollo-db-backup";

              serviceConfig = {
                EnvironmentFile = protonEnv;
                ExecStart = lib.getExe dbBackupScript;
                StateDirectory = "apollo-db-backup";
                StateDirectoryMode = "0700";
                TimeoutStartSec = "1800s";
                Type = "oneshot";

                NoNewPrivileges = true;
                PrivateTmp = true;
                ProtectHome = true;
                ProtectSystem = "strict";
                RestrictAddressFamilies = [
                  "AF_INET"
                  "AF_INET6"
                  "AF_UNIX"
                ];
              };
            };

            apollo-db-backup-alert = {
              description = "Notify on WhatsApp when the Apollo SQLite backup fails";

              serviceConfig = {
                ExecStart = lib.getExe dbBackupAlertScript;
                Type = "oneshot";

                NoNewPrivileges = true;
                ProtectHome = true;
                ProtectSystem = "strict";
                RestrictAddressFamilies = [
                  "AF_INET"
                  "AF_INET6"
                  "AF_UNIX"
                ];
              };
            };
          };

          timers.apollo-backup = {
            description = "Back up the Apollo workspace every 6 hours";

            timerConfig = {
              OnCalendar = "*-*-* 00/06:00:00";
              Persistent = true;
            };

            wantedBy = [ "timers.target" ];
          };

          timers.apollo-db-backup = {
            description = "Back up the Apollo SQLite database daily at 03:30";

            timerConfig = {
              OnCalendar = "*-*-* 03:30:00";
              Persistent = true;
            };

            wantedBy = [ "timers.target" ];
          };
        };

        time.timeZone = "Europe/Vienna";

        users.users.roman = {
          extraGroups = [ "wheel" ];
          isNormalUser = true;
          openssh.authorizedKeys.keys = [
            "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC2UfiONg3o2mydlSFdpIRWD9lRc+F/QK2GtHJPe3hYADJMFq+59gpYpuzA8Ccya6wGxkSUgcAWP5rqbidfsD08NzxQgCGz2HWyD0if0FkM2eeqOlOuJ5ymJ7NWnF1AQQBNE27UIPUW+beTlDCZEUZubSSfe87PEKbYgTeV7bO4BlXOzO+JI4AqUEuxQ5T6oFpUtKt+SepslsMECJZQnTBJBAITXBaBTwJwHYdNYx5WeK8+ObILPgapA0/l1/5y+zXBrU4ZH4xMSmlFNnt9iQxikrVXlWJvmieDfyPmkJSCJblqnhEmEgIyi+w/iPH5IwXaX8dwfp2mLM3ULSC5XvRPX7Pqs9gRmYAlaaFB7NEG2sEr8pWSq0Ag4enILp1otEvCLJtc/pbNa60rXiLpioOQ3kgsoMizsOHzqR7CN834dH3AK49zSKjEFVZLugzrB/GTsNH04+oQXbuDW04ok4b7xdy7fMPIA3I6TkaSHDfWAQ3DqaYdtmRzqlH3iljpVrTF6Mkjwuw8GZskblpx7AJXT7iH3CGXOVIf/qJnk806eDGKFwKLT/Pr86crmxbGdqiMIIM6UJ+0Ka+MMgaRrwi6h9FIRNUL6QM7/zC0QwNBxdGYtSOx58Z0qZ/LGqwm1qel2w0WIOkirbxLvk4Rbo+HedAZ8K38z9B7ZcCiN/U7bQ== roman@lerchster.dev"
          ];
        };
      };
  };
}
